######################################################################
# Automatically generated by qmake (2.01a) Fri Nov 25 22:44:48 2011
######################################################################

include(../common.pri)
include(../lib.pri)
include(../vtk.pri)
include(../itk.pri)

TEMPLATE = lib
TARGET = CSImages
DEPENDPATH += . filters
INCLUDEPATH += . filters

# Input
HEADERS += CSImage.h \
           filters/convertFilters/SkeletonImageToGraphFilter.h \
           filters/imageFilters/CSImageFilter.h \
           filters/imageFilters/exampleITKFilter.h \
           filters/imageFilters/itkBinaryThinningImageFilter3D.h \
           filters/imageFilters/MultiChannelBinaryThresholdImageFilter.h \
           filters/graphFilters/AnalyzeBileNetworkFilter.h \
           filters/graphFilters/AnalyzeGraphFilter.h \
           filters/graphFilters/GeometricalThresholdUndirectedGraphFilter.h \
           filters/graphFilters/ResampleUndirectedGraphFilter.h \
           pipelines/ExtractGraph.h \
           pipelines/SegmentBileNetworkOnDPPIV.h \
           pipelines/SegmentSinusoidalNetworkOnTwoChannels.h \
           tools/GraphAnnotationHelper.h

SOURCES += CSImage.cpp \
           filters/convertFilters/SkeletonImageToGraphFilter.cpp \
           filters/imageFilters/exampleITKFilter.cpp \
           filters/graphFilters/AnalyzeBileNetworkFilter.cpp \
           filters/graphFilters/AnalyzeGraphFilter.cpp \
           filters/graphFilters/GeometricalThresholdUndirectedGraphFilter.cpp \
           filters/graphFilters/ResampleUndirectedGraphFilter.cpp \
           pipelines/ExtractGraph.cpp \
           pipelines/SegmentBileNetworkOnDPPIV.cpp \
           pipelines/SegmentSinusoidalNetworkOnTwoChannels.cpp \
           tools/GraphAnnotationHelper.cpp
