######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 13 12:05:32 2012
######################################################################

TEMPLATE = lib

TARGET = CSCore


include(common.pri)
include(lib.pri)

CONFIG += qt

DESTDIR = ../lib

CONFIG += xml staticlib

win32:QMAKE_CXXFLAGS += /bigobj


DEPENDPATH += . \
              tools \
              tools/colors \
              tools/input \
              tools/math \
              tools/model \
              tools/output \
              tools/random \
			  tools/discvor \
              tools/sort \
              tools/threads \
              tools/triangulation \
              tools/new_triangulation \
              tools/new_triangulation/Geometry \
              tools/new_triangulation/IO \
              tools/new_triangulation/LinearAlgebra \
              tools/new_triangulation/MonteCarlo \
              tools/Vascularization \
              tools/dataIO \
              tools/dataIO/xml \
              tools/dataIO/hdf5 \
              tools/dataIO/vtp \
              tools/batchJob \
              model \
              model/Model \
              model/Model/ModelCellsTriangulated \
              model/Model/ModelCellsSpherical \
              model/Model/ModelCellsSphericalODE \
              model/Model/Vascularization \
              model/Elements \
              model/Interactions \
              model/BasicDatatypes \
              model/Cell \
              model/CellPopulation \
              model/Observation \
		   model/Lattice \
              gui \
              gui/GLTools \
              gui/graphTools

INCLUDEPATH += . \
               tools \
               tools/triangulation \	
               tools/new_triangulation \
               tools/new_triangulation/Geometry \
               tools/new_triangulation/IO \
               tools/new_triangulation/LinearAlgebra \
               tools/new_triangulation/MonteCarlo \
               tools/Vascularization \
               tools/math \
			   tools/discvor \
               tools/sort \
               tools/dataIO \
               tools/dataIO/xml \
               tools/dataIO/hdf5 \
               tools/dataIO/vtp \
               tools/batchJob \
               model \
               model/Model \
               model/Model/ModelCellsTriangulated \
               model/Model/ModelCellsSpherical \
               model/Model/ModelVacularization \
               model/Elements \
               model/Interactions \
               model/CellPopulation \
               model/Cell \
               model/BasicDatatypes \
               model/Observation \
               model/Vascularization_No \
		    model/Lattice \
               gui \
               gui/GLTools \
               gui/graphTools


# Input
HEADERS += Core.h \
           Version.h \
           tools/Tools.h \
           tools/colors/ColorTools.h \
           tools/input/FilenameParser.h \
           tools/model/CSModelTools.h \
           tools/model/BoundingBoxList.h \
           tools/model/CSSpaceDiscretization.h \
		tools/math/delaunay.h \
           tools/math/mathematics.h \
           tools/sort/sort.h \
           tools/output/OutputText.h \
           tools/parameters/CSParameter.h \
           tools/parameters/CSParameterTemporary.h \
           tools/parameters/CSParameterContext.h \
           tools/parameters/CSParameterContextTemporary.h \
           tools/parameters/CSParameterTreeItem.h \
           tools/parameters/CSParameterChoice.h \
           tools/random/Random.h \
           tools/triangulation/Mathematix.h \
           tools/triangulation/Triangulation.hpp \
           tools/triangulation/Mathematix.tcc \
           tools/new_triangulation/Geometry.hpp \
           tools/new_triangulation/IO.hpp \
           tools/new_triangulation/LinearAlgebra.hpp \
           tools/new_triangulation/MonteCarlo.hpp \
           tools/new_triangulation/MonteCarlo/Agent.hpp \
           tools/new_triangulation/MonteCarlo/Agent.ipp \
           tools/new_triangulation/MonteCarlo/Process.hpp \
           tools/new_triangulation/MonteCarlo/RuleBasedAgent.hpp \
           tools/new_triangulation/LinearAlgebra/finiteelements.hpp \
           tools/new_triangulation/LinearAlgebra/finiteelements.ipp \
           tools/new_triangulation/LinearAlgebra/mathematix.hpp \
           tools/new_triangulation/LinearAlgebra/mathematix.ipp \
           tools/new_triangulation/LinearAlgebra/matrix.hpp \
           tools/new_triangulation/LinearAlgebra/matrix.ipp \
           tools/new_triangulation/LinearAlgebra/matrix.hpp \
           tools/new_triangulation/LinearAlgebra/matrix.ipp \
           tools/new_triangulation/LinearAlgebra/solver.hpp \
           tools/new_triangulation/LinearAlgebra/solver.ipp \
           tools/new_triangulation/LinearAlgebra/sparsematrix.hpp \
           tools/new_triangulation/LinearAlgebra/sparsematrix.ipp \
           tools/new_triangulation/LinearAlgebra/sparsevector.hpp \
           tools/new_triangulation/LinearAlgebra/sparsevector.ipp \
           tools/new_triangulation/Geometry/array.h \
           tools/new_triangulation/Geometry/array2d.h \
           tools/new_triangulation/Geometry/datavertex.hpp \
           tools/new_triangulation/Geometry/datavertex.ipp \
           tools/new_triangulation/Geometry/numtraits.h \
           tools/new_triangulation/Geometry/octree.hpp \
           tools/new_triangulation/Geometry/array2d.h \
           tools/new_triangulation/Geometry/octree.ipp \
           tools/new_triangulation/Geometry/point3d.h \
           tools/new_triangulation/Geometry/shareddata.h \
           tools/new_triangulation/Geometry/tinyvector.h \
           tools/new_triangulation/Geometry/triangulation.hpp \
           tools/new_triangulation/Geometry/triangulation.ipp \
           tools/new_triangulation/IO/EPS.hpp \
           tools/new_triangulation/IO/EPS.ipp \
           tools/new_triangulation/IO/Povray.hpp \
           tools/new_triangulation/IO/Povray.ipp \
           tools/new_triangulation/IO/tinystr.h \
           tools/new_triangulation/IO/tinyvector.h \
           tools/new_triangulation/IO/tinyxml.h \
           tools/dataIO/xml/CSXMLWriter.h \
           tools/dataIO/xml/CSXMLReader.h \
           tools/dataIO/hdf5/CSHDF5Writer.h \
           tools/dataIO/hdf5/CSHDF5Reader.h \
           tools/dataIO/vtp/CSVTPWriter.h \
           tools/dataIO/CSDataWriter.h \
           tools/dataIO/CSDataReader.h \
           tools/batchJob/CSBatchJob.h \
		   tools/discvor/discvor.h \
           model/Interactions/CSInteraction.h \
           model/Interactions/CSInteractionJKR.h \
           model/Interactions/CSInteractionHertz.h \
           model/Interactions/CSInteractionFrictionMatrix.h \
           model/BasicDatatypes/Vector.h \
           model/BasicDatatypes/Graph.h \
           model/BasicDatatypes/GraphSphere.h \
           model/BasicDatatypes/BoundingBox.h \
           model/BasicDatatypes/Color.h \
           model/BasicDatatypes/MassPoint.h \
           model/BasicDatatypes/Spring.h \
           model/BasicDatatypes/Triangle.h \
		model/BasicDatatypes/Utils.h \
           model/BasicDatatypes/CSListContainer.h \
           model/Elements/ModelElement.h \
           model/Elements/ModelElementSphere.h \
           model/Elements/ModelElementTriangulated.h \
           model/Elements/ModelElementVesselSphere.h \
		model/Elements/ModelElementECMSphere.h \
           model/Elements/ModelElementBarrierTriangle.h \
           model/Elements/ModelElement_VesselGraph.h \
           model/Elements/ModelElementHollowSphere.h \
           model/Cell/Cell.h \
           model/Cell/CellSpherical.h \
           model/Cell/CellSphericalODE.h \
           model/Cell/CellTriangulated.h \
           model/Cell/CellSphericalPolar.h \
           model/CellPopulation/CellPopulation.h \
           model/Model/BiologyLink.h \
           model/Model/CSModel.h \
           model/Model/ModelCellsSpherical/ModelCellsSpherical.h \
           model/Model/ModelCellsSpherical/LobuleLesionVoxelization.h \
           model/Model/ModelCellsSphericalODE/ModelCellsSphericalODE.h \
           model/Model/ModelCellsTriangulated/Model3D.h \
           model/Model/Models.h \
           model/Observation/Observation.h \
           model/Model/ModelVascularization/VesselGraph.hpp \
           model/Model/ModelVascularization/CSVesselGraph.h \
           model/Model/ModelVascularization/VoronoiDiagram.hpp \
           model/Model/ModelVascularization/ModelVascularization.h \
           model/Model/ModelVascularization/Cells.hpp \
           model/Model/ModelVascularization/Tumor.hpp \
           model/Model/ModelVascularization/Perfusion.cpp \
           model/Vascularization_No/Model_Vascularization_No.h \
		model/Lattice/Function.h \
		model/Lattice/LatticeSpring.h \
		model/Lattice/LinearFunction.h \
		model/Lattice/LinearSpring.h \
		model/Lattice/ModelElementFibre.h \
		model/Lattice/ModelElementLatticeNode.h \
		model/Lattice/ModelLattice.h \
		model/Lattice/NonLinearStiffeningFunction.h \
		model/Lattice/RotationalSpring.h \
		model/Lattice/SimulationObject.h \
           gui/CSGLArena.h \
           gui/CSGLObject.h \
           gui/GLTools/TriangulatedCell.h \
           gui/GLTools/CSGLVascularization.h \
		gui/GLTools/CSGLBar.h \
           gui/GLTools/CSGLSphere.h \
           gui/GLTools/CSGLTriangle.h \
           gui/QCSParameterDelegate.h

SOURCES += Core.cpp \
           tools/Tools.cpp \
           tools/colors/ColorTools.cpp \
           tools/input/FilenameParser.cpp \
           tools/model/BoundingBoxList.cpp \
           tools/model/CSSpaceDiscretization.cpp \
		tools/math/delaunay.cpp \
           tools/math/mathematics.cpp \
           tools/output/OutputText.cpp \
           tools/parameters/CSParameter.cpp \
           tools/parameters/CSParameterTemporary.cpp \
           tools/parameters/CSParameterContext.cpp \
           tools/parameters/CSParameterContextTemporary.cpp \
           tools/parameters/CSParameterChoice.cpp \
           tools/random/Random.cpp \
           tools/triangulation/Mathematix.cpp \
           tools/triangulation/Triangulation.cpp \
           tools/new_triangulation/MonteCarlo/Agent.cpp \
           tools/new_triangulation/MonteCarlo/Process.cpp \
           tools/new_triangulation/MonteCarlo/RuleBasedAgent.cpp \
           tools/new_triangulation/LinearAlgebra/Finiteelements.cpp \
           tools/new_triangulation/LinearAlgebra/Mathematix.cpp \
           tools/new_triangulation/Geometry/DataVertex.cpp \
           tools/new_triangulation/IO/EPS.cpp \
           tools/new_triangulation/IO/Povray.cpp \
           tools/new_triangulation/IO/tinystr.cpp \
           tools/new_triangulation/IO/tinyxmlerror.cpp \
           tools/new_triangulation/IO/tinyxmlparser.cpp \
           tools/new_triangulation/IO/tinyxml.cpp \
           tools/sort/sort.cpp \
           tools/dataIO/xml/CSXMLWriter.cpp \
           tools/dataIO/xml/CSXMLReader.cpp \
           tools/dataIO/hdf5/CSHDF5Writer.cpp \
           tools/dataIO/hdf5/CSHDF5Reader.cpp \
           tools/dataIO/vtp/CSVTPWriter.cpp \
           tools/dataIO/CSDataWriter.cpp \
           tools/dataIO/CSDataReader.cpp \
           tools/batchJob/CSBatchJob.cpp \
		   tools/discvor/discvor.cpp \
           model/Interactions/CSInteractionJKR.cpp \
           model/Interactions/CSInteractionHertz.cpp \
           model/Interactions/CSInteractionFrictionMatrix.cpp \
           model/BasicDatatypes/Vector.cpp \
           model/BasicDatatypes/Graph.cpp \
           model/BasicDatatypes/GraphSphere.cpp \
           model/BasicDatatypes/MassPoint.cpp \
           model/BasicDatatypes/Spring.cpp \
           model/BasicDatatypes/Triangle.cpp \
		model/BasicDatatypes/Utils.cpp \
           model/Elements/ModelElement.cpp \
           model/Elements/ModelElementSphere.cpp \
           model/Elements/ModelElementTriangulated.cpp \
           model/Elements/ModelElementVesselSphere.cpp \
		model/Elements/ModelElementECMSphere.cpp \
           model/Elements/ModelElementBarrierTriangle.cpp \
           model/Elements/ModelElement_VesselGraph.cpp \
           model/Elements/ModelElementHollowSphere.cpp \
           model/Cell/Cell.cpp \
           model/Cell/CellSpherical.cpp \
           model/Cell/CellSphericalODE.cpp \
           model/Cell/CellTriangulated.cpp \
           model/CellPopulation/CellPopulation.cpp \
 #          model/CellPopulation/CellPopulationTriangulated.cpp \
           model/Model/BiologyLink.cpp \
           model/Model/CSModel.cpp \
           model/Model/ModelCellsSpherical/ModelCellsSpherical.cpp \
           model/Model/ModelCellsSpherical/LobuleLesionVoxelization.cpp \
           model/Model/ModelCellsSphericalODE/ModelCellsSphericalODE.cpp \
           model/Cell/CellSphericalPolar.cpp \
           model/Model/ModelCellsTriangulated/Model3D.cpp \
           model/Observation/Observation.cpp \
           model/Model/ModelVascularization/VesselGraph.cpp \
           model/Model/ModelVascularization/CSVesselGraph.cpp \
           model/Model/ModelVascularization/Tumor.cpp \
           model/Model/ModelVascularization/ModelVascularization.cpp \
           model/Vascularization_No/Model_Vascularization_No.cpp \
		model/Lattice/Function.cpp \
		model/Lattice/LatticeSpring.cpp \
		model/Lattice/LinearFunction.cpp \
		model/Lattice/LinearSpring.cpp \
		model/Lattice/ModelElementFibre.cpp \
		model/Lattice/ModelElementLatticeNode.cpp \
		model/Lattice/ModelLattice.cpp \
		model/Lattice/NonLinearStiffeningFunction.cpp \
		model/Lattice/RotationalSpring.cpp \
		model/Lattice/SimulationObject.cpp \
           gui/CSGLArena.cpp \
           gui/CSGLObject.cpp \
		gui/GLTools/CSGLBar.cpp \
           gui/GLTools/CSGLSphere.cpp \
           gui/GLTools/CSGLTriangle.cpp \
           gui/GLTools/CSGLVascularization.cpp \
           gui/GLTools/TriangulatedCell.cpp \
           gui/QCSParameterDelegate.cpp
